<?php

namespace Tests\Feature;


use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ApplicationTest extends TestCase
{
    use RefreshDatabase;

    public $token;
    public $user;

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
        $this->actingAs($this->user);
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_application_index()
    {
        $response = $this->withHeaders([
            'Accept' => 'application/json',
            'Authorization' => 'Bearer ' . $this->user->access_token
        ])
            ->json(
                'get',
                '/api/users/applications',
            );
        $response->assertJson(["success" => true]);
        //    echo json_encode($response);
        $response->assertStatus(200);

    }


    public function test_application_creation()
    {
        $response = $this->withHeaders([
            'Accept' => 'application/json',
            'Authorization' => 'Bearer ' . $this->user->access_token
        ])
            ->json(
                'post',
                '/api/users/applications',
                [
                    "code" => "test",
                    "name_en" => "test1",
                    "age" => "12",
                    "birth_date" => "2000-10-10",
//                    "gender" => ,
//                    "marital_status" =>  ,
//                    "housemaid_price" => ,
//                    "salary" => ,
//                    "external_office_id" => ,
//                    "internal_office_id" => ,
//                    "passport_no"

                ]
            );
        $response->assertJson(["success" => true]);
        //    echo json_encode($response);
        $response->assertStatus(200);
    }
//    public function test_application_reservation_creation()
//    {
//
//    }
//    public function test_application_reservation()
//    {
//        $user = User::factory()->create();
//        $this->actingAs($user);
//        $response = $this->withHeaders([
//            'Accept' => 'application/json',
//            'Authorization' => 'Bearer ' .  $user->access_token
//        ])
//            ->json(
//                'post',
//                '/api/users/application_reservations',
//                [
//                    "application_id" => 1,
//                    "sponsor_id" => "1",
//                    "reservation_date" => "2022 - 07 - 01",
//                    "note" => "test2",
//                    "passport_id" => "1",
//                    "reservation_days" => "1",
//                    "deal_amount" => "1500",
//                    "down_payment_amount" => "100",
//                    "paid_immediately" => "0",
//                    "pay_due_date" => "2022 - 09 - 01",
//                ]
//            );
//        $response->assertStatus(200);
//
//    }
}
